// starter/src/App.jsx
import { useState } from 'react';
import  data  from './data';
import List from './List';
const App = () => {
  const [people, setPeople] = useState(data);

  return (
    <main>
      <section className='container'>
        <h3>{people.length} Birthdays</h3>
        <List people={people} />
        <button className='btn btn-block' onClick={() => setPeople([])}>Clear All</button>
      </section>
    </main>
  )
};
export default App;

// vue-version/src/App.vue
<script setup>
  import { ref } from 'vue'
  import  data from './data'
  import List from './components/List.vue';
  
  const people = ref(data)
</script>

<template>
  <main>
    <section>
      <h3>{{ people.length }} Birthdays</h3>
      <List :people="people" />
      <button class="btn btn-block" @click="people.length = 0">Clear All</button>
    </section>
  </main>
</template>
